---
# vars file for full_config
device:
      ip_address: '{{ ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

    interfaces:
      - if_name: 'ethernet1/1'
        mode: 'layer3'
        ip: ['192.168.55.20/24']
        enable_dhcp: false
      - if_name: 'ethernet1/2'
        mode: 'layer3'
        ip: ['192.168.45.20/24']
        enable_dhcp: false
      - if_name: 'ethernet1/3'
        mode: 'layer3'
        ip: ['192.168.35.20/24']
        enable_dhcp: false

    zones:
      - zone: 'untrust'
        mode: 'layer3'
        interfaces: ['ethernet1/1']
      - zone: 'web'
        mode: 'layer3'
        interfaces: ['ethernet1/2']
      - zone: 'db'
        mode: 'layer3'
        interfaces: ['ethernet1/3']

    address_objects:
      - name: 'web-srv'
        value: '192.168.45.5'
      - name: 'db-srv'
        value: '192.168.35.5'

    service_objects:
      - name: 'service-tcp-221'
        protocol: 'tcp'
        destination_port: '221'
      - name: 'service-tcp-222'
        protocol: 'tcp'
        destination_port: '222'

    security_rules:
      - rule_name: 'Allow ping'
        source_zone: ['any']
        source_ip: ['any']
        destination_zone: ['any']
        destination_ip: ['any']
        application: ['ping']
        service: ['application-default']
        action: 'allow'

      - rule_name: 'Allow SSH inbound'
        source_zone: ['untrust']
        source_ip: ['any']
        destination_zone: ['web', 'db']
        destination_ip: 'any'
        application: ['ssh']
        service: ['service-tcp-221', 'service-tcp-222']
        action: 'allow'

      - rule_name: 'Add web inbound rule'
        source_zone: ['untrust']
        source_ip: ['any']
        destination_zone: ['web']
        destination_ip: ['any']
        application: ['web-browsing', 'ssl', 'blog-posting']
        service: ['application-default']
        action: 'allow'

      - rule_name: 'Allow web to db'
        source_zone: ['web']
        source_ip: ['web-srv']
        destination_zone: ['db']
        destination_ip: ['db-srv']
        application: ['mysql']
        service: ['application-default']
        action: 'allow'

      - rule_name: 'Allow all outbound'
        source_zone: ['web', 'db']
        source_ip: ['any']
        destination_zone: ['untrust']
        destination_ip: ['any']
        application: ['any']
        service: ['application-default']
        action: 'allow'

    inbound_nat_rules:
      - rule_name: 'Web SSH'
        source_zone: ['untrust']
        source_ip: ['any']
        destination_zone: 'untrust'
        destination_ip: ['10.5.1.4']
        service: 'service-tcp-221'
        snat_type: 'dynamic-ip-and-port'
        snat_interface: 'ethernet1/2'
        dnat_address: 'web-srv'
        dnat_port: '22'

      - rule_name: 'DB SSH'
        source_zone: ['untrust']
        source_ip: ['any']
        destination_zone: 'untrust'
        destination_ip: ['10.5.1.4']
        service: 'service-tcp-222'
        snat_type: 'dynamic-ip-and-port'
        snat_interface: 'ethernet1/2'
        dnat_address: 'db-srv'
        dnat_port: '22'

      - rule_name: 'WordPress NAT'
        source_zone: ['untrust']
        source_ip: ['any']
        destination_zone: 'untrust'
        destination_ip: ['10.5.1.4']
        service: 'service-http'
        snat_type: 'dynamic-ip-and-port'
        snat_interface: 'ethernet1/2'
        dnat_address: 'web-srv'
        dnat_port: '80'
